export { default as Motion } from './motion.vue'
export { default as BaseWidget } from './widgets/base-widget.vue'
export * from './widgets/base-widget'
export { default as Rect } from './widgets/rect.vue'
export * from './widgets/rect'
export { default as Polygon } from './widgets/polygon.vue'
export * from './widgets/polygon'
export { default as Arc } from './widgets/arc.vue'
export * from './widgets/arc'
export { default as Line } from './widgets/line.vue'
export * from './widgets/line'
export { default as Group } from './widgets/group.vue'
export * from './widgets/group'
export { default as Text } from './widgets/text.vue'
export * from './widgets/text'
export { default as TextItem } from './widgets/text-item.vue'
export * from './widgets/text-item'
export { default as Webview } from './widgets/webview.vue'
export * from './widgets/webview'

export * from './widgets/figure'

export * from './animations/move'
export * from './animations/create'
export * from './animations/delay'
export * from './animations/stroke'
export * from './animations/stroke-fill'
export * from './animations/focus-on'
export * from './animations/rotate'
export * from './animations/scale'
export * from './animations/indicate'
export * from './animations/circle-indicate'