export { widget } from './widget'
export type { WidgetOptions } from './widget'
export { figure } from './figure'
export type { FigureOptions } from './figure'
export { default as Group } from './group.vue'

export { default as Arc } from './arc.vue'
export type { ArcOptions } from './arc.vue'
export { default as Line } from './line.vue'
export type { LineOptions } from './line.vue'
export { default as Polygon } from './polygon.vue'
export type { PolygonOptions } from './polygon.vue'
export { default as Rect } from './rect.vue'
export type { RectOptions } from './rect.vue'
export { default as Text } from './text.vue'
export type { TextOptions } from './text.vue'
